# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  run-on-instance:
    strategy:
      matrix:
        label: [ah-ubuntu_22_04-c7g_x-50, ah_ubuntu_22_04_c6g_x_50, ah_ubuntu_22_04_c6g_2x_50, ah_ubuntu_22_04_c7g_2x_50, ah_ubuntu_22_04_c6g_8x_100, ah_ubuntu_22_04_c7g_8x_100, ah_ubuntu_22_04_c7g_4x_50, ah_ubuntu_22_04_c7g_8x_50]
        
    # The type of runner that the job will run on
    runs-on: ${{ matrix.label }}

    steps:
      - name: Run a command
        run: echo Hello, world!

      # Runs sudo docker
      - name: Runs docker
        run: |
          docker run hello-world

      # Runs sudo docker
      - name: Runs sudo docker
        run: |
          sudo docker run hello-world
          
  run-on-container:
    strategy:
      matrix:
        label: [ah-ubuntu_22_04-c7g_x-50, ah_ubuntu_22_04_c6g_x_50, ah_ubuntu_22_04_c6g_2x_50, ah_ubuntu_22_04_c7g_2x_50, ah_ubuntu_22_04_c6g_8x_100, ah_ubuntu_22_04_c7g_8x_100, ah_ubuntu_22_04_c7g_4x_50, ah_ubuntu_22_04_c7g_8x_50]
    runs-on: ${{ matrix.label }}
    container:
      image: ubuntu
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
